project:
  type: website
  output-dir: docs

website:
  title: "Sayak Mukherjee"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Publications
      - href: teaching
        text: Teaching
      - href: posts
        text: Blog
  page-footer:
    left: >-
      &copy; 2025 Sayak Mukherjee &#8729; Made with [Quarto](https://quarto.org)
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      dark: 
        - cosmo
        - style/theme-dark.scss
      light:
        - cosmo
        - style/theme-light.scss
    # css: styles.css
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center



